# Generated by Django 4.1.5 on 2023-01-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not set', max_length=50)),
                ('temp', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('next_spray', models.TimeField()),
                ('fertilizer_level', models.IntegerField(default=0)),
                ('led_intensity', models.IntegerField(default=0)),
                ('time_to_sundown', models.TimeField()),
                ('status', models.CharField(choices=[('H', 'Healthy'), ('I', 'Infected'), ('W', 'Withered'), ('N', 'No stats available')], default='N', max_length=1)),
            ],
        ),
    ]
