# Generated by Django 4.1.5 on 2023-01-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_plantdata_fertilizer_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='next_spray',
            field=models.IntegerField(default=0),
        ),
    ]
