# Generated by Django 4.1.5 on 2023-01-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_plantdata_next_spray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='status',
            field=models.CharField(default='No stats', max_length=20),
        ),
    ]
